name: Keep Streamlit Awake

on:
  schedule:
    - cron: '0 */10 * * *'  # Every 10 hours, at minute 0
  # workflow_dispatch: # for manual trigger

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Streamlit App
        run: curl -sSf https://accelerated-ai-progress.streamlit.app/
